**<font color = black size=6>实验五:决策树</font>**

**<font color = blue size=4>第一部分:函数介绍</font>**

In [1]:
from collections import Counter
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math

1)Counter类的使用

In [2]:
x=np.array([[0,133,1],[0,132,0],[0,133,0]])
#使用Counter类对数组第2列进行遍历
counter = Counter(x[:,1])
#第2列中有1个132和2个133，输出该counter对象可以统计这列的数值情况，便于之后的统计
print(counter)
#因为第2列中没有为0的值，所以返回0
print(counter[0])
#因为第2列中有2个133，所以返回2
print(counter[133])
#一般的字典操作方法都能在该类中使用，例如可以通过values函数返回该列的非重复值的个数，方便对某列的非重复值的个数进行查看
print(counter.values())
#可以输出所有非重复值
print(list(counter))

Counter({133: 2, 132: 1})
0
2
dict_values([2, 1])
[133, 132]


2)使用numpy中的unique实现非重复值的提取

In [3]:
x=np.array([[0,133,1],[0,132,0],[0,133,0]])
# 提取整个x矩阵中的非重复值
a=np.unique(x[:])
# 提取x矩阵中第2列的非重复值
a1=np.unique(x[:,1])
print(a,a1)

[  0   1 132 133] [132 133]


**<font color = blue size=4>第二部分:实验任务</font>**

**<font color = blue size=3>1) 任务一</font>**

任务一要求完成不同量化标准(信息增益, 信息增益率, 基尼系数)下的结点划分函数

<span style="color:purple">该数据集(train_titanic.csv)为分类数据集，为泰坦尼克号的部分乘客信息以及最后是否生还。包括了四个属性特征以及一个标签(即为Survived,代表是否生还),属性特征分别为Sex(性别)，sibsp(堂兄弟妹个数)，Parch(父母与小孩的个数)，Pclass(乘客等级)  
其中该数据集无缺失值和异常值，且所有连续变量已自动转换为离散变量,标签(Survived)也自动转变为离散变量0和1，所以你无需进行数据预处理，可以直接使用该数据集。</span>

<span style="color:purple">1) 使用pandas库将训练数据集'train_titanic.csv'载入到Dataframe对象中</span>

In [ ]:
#----your code here
train_frame = pd.read_csv('train_titanic.csv')

train_feature=train_frame
train_outcome=train_frame[['Survived']]

train_f = np.array(train_feature)
train_o = np.array(train_outcome)

train_f = train_f[:,0:4]
# 留意特征数组和标签数组的形状
print(train_f)
print(train_o)

[[0 1 0 3]
 [1 1 0 1]
 [1 0 0 3]
 ...
 [0 0 0 3]
 [0 0 0 3]
 [0 1 1 3]]
[[0]
 [1]
 [1]
 ...
 [0]
 [0]
 [0]]


<span style="color:purple">2) 编写函数，给定任何标签数组计算其信息熵  
    输入：标签数组  
    输出：该数组对应的信息熵  
    计算信息熵公式:
某数组包含K个不同的取值，样本为第k(k=1,2,...,K)个值的数量所占比例为p_k,则其信息熵为$$Ent=-\sum_{k=1}^K p_k log_2 p_k$$</span>
    
    
<span style="color:purple">例:  
    输入:[[0],[1]]   
    输出:(-$\frac{1}{2}$ $log_2$ $\frac{1}{2}$)+(-$\frac{1}{2}$ $log_2$ $\frac{1}{2}$)=1</span>

In [ ]:
# 下面是计算信息熵的函数
# 其输入是数据集的标签数组，输出是该标签数组的信息熵
# 请补全这个函数的代码，计算信息熵
def entropy(label):
    # 如果传入的 label 是 Python 的 set（无序且不可按索引访问），
    # 先将其转换为 list 再用 np.array 转为 NumPy 数组，以便后续能使用 NumPy 的索引、切片或按维度处理。
    # 这样可以保证后续对 label 的计数/统计操作（如 Counter 或按列取值）正常工作。
    if isinstance(label, set):
        label=np.array(list(label))
    if label.ndim==1:
        counter = Counter(label)
    else:
        counter = Counter(label[:,0])
    ent = 0.0
    # 请补全下面的代码，计算信息熵
    # -------Your Code Here-------
    # Tips: 遍历counter.values()，计算每个类别的概率，然后计算信息熵
    for  in :
        # Tips: 计算标签数组中每个标签出现的概率
        p = 
        # Tips: 计算信息熵-p*log2(p)，并累加到ent变量中。可使用math.log2函数计算以2为底的对数
        ent += 
    return ent

<span style="color:purple">3) 编写函数，函数功能为将所给的数据集按照指定维度的特征进行划分为若干个不同的数据集  
    【输入】：特征集合，标签集合，指定维度  
    【输出】：划分后所得到的子数据集特征集合，子数据集标签集合</span>

<span style="color:purple">例子:  
    【输入】:特征集合:[[0,0,0],[0,0,1],[1,0,2]]  
    标签集合:[[0],[1],[2]]  
    指定维度:0</span>  
    
<span style="color:purple">【输出】:[[0,0,0],[0,0,1]]和[[1,0,2]]  
    [[0],[1]]和[[2]]  
    tips:即将特征按其第0维度进行划分，由于第0维特征有0和1两个不同的数值，所以特征集合划分为[[0,0,0],[0,0,1]]和[[1,0,2]]，标签集合划分为[[0],[1]]和[[2]]</span>

In [ ]:
# 我们给出一个划分数据集的函数split，请对这个函数进行填空，补全其实现
# 该函数的输入是数据集的特征矩阵feature，标签数组label，以及划分的维度d
# 该函数的输出是划分后的特征子集列表split_feature和标签子集列表split_label
# 例如，假设feature是一个形状为(n_samples, n_features)的NumPy数组，label是一个形状为(n_samples,)的NumPy数组
# 则split(feature, label, d)会返回两个列表：
# split_feature = [feature_subset_1, feature_subset_2, ..., feature_subset_k]
# split_label = [label_subset_1, label_subset_2, ..., label_subset_k]
# 其中k是特征的第d列中唯一值的个数，feature_subset_i是feature中第d列等于某个唯一值的所有样本构成的子集，label_subset_i是对应的标签子集

# 请补全下面的代码，计算信息熵
def split(feature, label, d):
    # 使用 np.unique() 函数获取特征矩阵feature的第 d 列中的唯一值列表 unique_vals
    # -------Your Code Here-------
    unique_vals=
    if isinstance(label, set):
        label=np.array(list(label))
    split_feature=[]
    split_label=[]
    for i in range(len(unique_vals)):
        #    使用表达式 (feature[:,d] == unique_vals[i]) 获取特征矩阵中第 d 列等于 unique_vals[i] 的布尔索引 indices。
        #    将满足条件的特征子集 feature[indices] 添加到 split_feature 列表。
        #    将对应的标签子集 label[indices] 添加到 split_label 列表。
        # -------Your Code Here-------
        indices=
        split_feature.append()
        split_label.append()
    return split_feature,split_label

# Tips:此处会用到的函数
# 1.np.unique()
# ---------------------
# np.unique() 是 NumPy 库中的一个函数，用于提取数组中所有不重复的元素，并返回一个按照升序排序的一维数组。
# 它常用于数据去重、统计数组中不同元素的个数或寻找数据集中出现的所有唯一值。
#
# 示例：
#   import numpy as np
#   arr = np.array([4, 2, 2, 8, 4, 6])
#   unique_arr = np.unique(arr)
#   # unique_arr 的输出为: array([2, 4, 6, 8])
#
#
# 2. Python 布尔索引：
# -------------------------
# 布尔索引允许我们通过一个布尔（True/False）数组来从原始数组中筛选出满足特定条件的元素，
# 而不需要显式地写循环。条件表达式会返回一个与原始数组形状相同的布尔数组，然后将该布尔数组作为索引，
# 得到所有对应位置为 True 的元素。
#
# 示例：
#   import numpy as np
#   arr = np.array([10, 15, 20, 25, 30])
#   condition = arr > 20   # 得到布尔数组: array([False, False, False, True, True])
#   filtered_arr = arr[condition]
#   # filtered_arr 的输出为: array([25, 30])

<span style="color:purple">4) 编写函数，遍历找出该特征集合中信息增益(使用ID3算法中的公式计算)【最大】的特征  
    输入：特征集合，标签集合  
    输出：该次划分的最佳信息增益值，最佳划分维度  
    计算信息增益公式:  
    某数据集D有若干特征值以及对应的标签值，其总样本大小为|D|,这里取其中一个特征feature,该特征包含V个不同的取值，其中值为第v(v=1,2,...,V)个值的样本数量为|$D^v$|，$(此处有\sum_{v=1}^VD^v=|D|)$,则该特征值对应的信息增益为$$Gain(D,feature)=Ent(D)-\sum_{v=1}^K \frac{|D^v|}{D} Ent(D^v)$$
该函数中你需要计算出每个特征的信息增益，然后返回最佳的信息增益值和对应的特征的维数</span>

In [ ]:
# 请按照下面的实现思路，补全find_opt_feature_gain的代码，计算信息增益
# 实现思路：
# 1. 首先计算整体标签 y_label 的熵 Ent。
# 2. 对于每个特征列（即每个维度 d）：
#     a. 调用 split() 函数，将数据按照该特征的不同取值进行划分，
#         得到子特征集合 feature 和对应的子标签集合 label。
#     b. 对每个划分好的子数据集，计算该子数据集的熵，并根据该子集在原始数据中的比例加权，
#         得到该特征划分后的加权熵总和。
#     c. 用整体熵 Ent 减去加权熵，就得到了该特征的“信息增益”。
# 3. 比较所有特征的信息增益，选择信息增益最大的特征作为最佳划分特征。

# Tips: 可能会用到的函数和语法：
#     - entropy(): 前面实现的函数，计算给定标签集的熵值。
#     - split(): 前面实现的函数，按照指定特征对数据进行划分，生成不同取值对应的数据子集。


def find_opt_feature_gain(x_data, y_label):
    best_gain = -float('inf')
    best_dimension = -1
    # 使用前面实现的entropy()函数计算整体标签 y_label 的熵 Ent。
    # ----- Your Code Here-----
    Ent=
    
    for d in range(x_data.shape[1]):
        # 使用前面实现的split函数将数据集按照维度d进行划分
        # ----- Your Code Here-----
        feature,label= 
        gain,ent = 0, 0
        # 遍历每个划分好的子数据集，并计算该子数据集的加权熵
        for i in range(len(feature)):
            # 计算该子数据集的加权熵
            # 权重|Dv|/|D|为feature[i]的大小除以x_data的大小
            # 使用entropy()函数计算label[i]的信息熵
            # ----- Your Code Here ------
            ent+=
        gain=Ent-ent
        if gain > best_gain:
            # 记录最优的信息增益和此时的划分维度
            # ------ Your Code Here ------
            best_gain = 
            best_dimension = 
                
    return best_gain, best_dimension

<span style="color:purple">5) 编写函数，遍历找出该特征集合中信息增益率(使用C4.5算法中的公式计算)【最大】的特征  
    输入：特征集合，标签集合  
    输出：最佳划分的信息增益率值，对应的划分维度  
    计算信息增益率公式:  
    某数据集D有若干特征值以及对应的标签值，其总样本大小为|D|,这里取其中一个特征类型feature,该特征包含V个不同的取值，值为第v(v=1,2,...,V)个值的样本数量为|$D^v$|,该特征列本身的信息熵为Ent(feature),则该特征值对应的信息增益率为$$Gain\_ratio(D,feature)=\frac{Gain(D,feature)}{Ent(feature)}$$  
该函数中你需要计算每个特征的信息增益率，之后返回最佳的信息增益率和对应的特征维数</span>

In [ ]:
# 请按照下面的实现思路，补全find_opt_feature_gainratio的代码，计算信息增益率
# 实现思路：
# 1. 首先计算整体标签 y_label 的熵 Ent。
# 2. 对于每个特征列（即每个维度 d）：
#     a. 调用 split() 函数，将数据按照该特征的不同取值进行划分，
#         得到子特征集合 feature 和对应的子标签集合 label。
#     b. 对每个划分好的子数据集，计算该子数据集的熵，并根据该子集在原始数据中的比例加权，
#         得到该特征划分后的加权熵总和。
#     c. 用整体熵 Ent 减去加权熵，得到该特征的信息增益。
#     d. 计算该特征本身的熵 Ent(feature)。
#     e. 用信息增益除以特征熵，得到该特征的信息增益率。
# 3. 比较所有特征的信息增益率，选择信息增益率最大的特征作为最佳划分特征。
# Tips: 可能会用到的函数和语法：
#     - entropy(): 前面实现的函数，计算给定标签集的熵值。
#     - split(): 前面实现的函数，按照指定特征对数据进行划分，生成不同取值对应的数据子集。

def find_opt_feature_gainratio(x_data, y_label):
    best_ratio = -float('inf')
    best_dimension = -1
    # 使用前面实现的entropy()函数计算整体标签 y_label 的熵 Ent。
    # ----- Your Code Here-----
    Ent=
    for d in range(x_data.shape[1]):
        # 使用前面实现的split函数将数据集按照维度d进行划分
        # ----- Your Code Here-----
        feature,label= 
        gain,ent = 0, 0
        for i in range(len(feature)):
            # 计算该子数据集的加权熵
            # 权重|Dv|/|D|为feature[i]的大小除以x_data的大小
            # 使用entropy()函数计算label[i]的信息熵
            # ----- Your Code Here ------
            ent+=
        # 计算d维特征x_data[:,d]本身的熵，即Ent(feature)
        # Tips: 使用前面实现的entropy()函数
        # ----- Your Code Here ------
        ent_feature=
        if ent_feature!=0:
            # 计算d维特征的信息增益和信息增益率
            # ----- Your Code Here ------
            gain=
            gain_ratio=
            if gain_ratio > best_ratio:
                best_ratio = gain_ratio
                best_dimension = d
    return best_ratio, best_dimension

<span style="color:purple">6) 编写函数，遍历找出该特征集合中基尼系数(使用CART算法中的公式计算)最小的特征以及最佳的划分值  
    输入：特征集合，标签集合  
    输出：最佳的基尼系数，对应的划分维度，最佳划分值  
    计算基尼系数公式:  
    某数据集D有若干特征值以及对应的标签值，其总样本大小为|D|,该集合中标签类别总共有K类，第k类样本所占比例为$p_k$(k=1,2,..,K),则该数据集对应的基尼系数为$$Gini(D)=1-\sum_{k=1}^K{p_k}^2$$  
    而取其中一个特征feature，选定该特征的一个值value，根据该特征的值是否为value将数据集分为两个子集$D_1$和$D_2$,则该特征对应的基尼系数为$$Gini\_index(D,feature)=\frac{|D_1|}{|D|}Gini(D_1)+\frac{|D_2|}{|D|}Gini(D_2)$$
该函数中你需要遍历每一列特征，找出每列中的非重复值，计算出每个非重复值的基尼系数，返回最小的基尼系数、对应的特征维数和非重复值（分类值）。</span>

In [ ]:
# Tips:可能用到的函数和语法：
# - np.unique():
#     提取数组中的所有不重复元素，并返回一个排好序的一维数组，
#     用于提取某个特征 d 中的非重复值
#     例如 np.unique([3, 1, 2, 2]) 得到 [1, 2, 3]。
# - 布尔索引:
#     (x_data[:, d] == unique_values[i]) 会对 x_data 的第 d 列进行逐元素比较，
#     返回一个布尔数组，指明哪些样本的该列值等于 unique_values[i]。使用此布尔数组可以从原数组中直接筛选出符合条件的行。
# - Counter:
#     用于统计列表或数组中各元素出现的次数，
#     例如 Counter([1, 2, 2, 3]) 返回 {1: 1, 2: 2, 3: 1}。
#     在这里，Counter 用于统计不同标签在某个子集中的分布情况，
#     获得 K 类标签中每一类样本的个数

def find_opt_feature_gini(x_data, y_label):
    best_gini = float('inf')
    best_dimension = -1
    #遍历 x_data 中的每个特征 d:
    for d in range(x_data.shape[1]):
        # 使用np.unique()计算特征 d 的唯一取值集合 unique_values
        # -------Your Code Here-------
        unique_values=
        
        #遍历 unique_values 中的每个取值 v:
        for i in range(len(unique_values)):
            gini_sum=0
            # ---- Your Code Here -----
            #选取 x_data[:, d] == v 的样本索引
            indice_v=(x_data[:,d] == )
            #选取 x_data[:, d] != v 的样本索引
            indice_nv=(x_data[:,d] != )

            y_v, y_nv = y_label[indice_v,0], y_label[indice_nv,0]
            n_v, n_nv = len(y_v), len(y_nv)

            counter_yv, counter_ynv = Counter(y_v), Counter(y_nv)
            # 计算特征 d 取值为 v 的子数据集的基尼系数 gini_v
            temp_v = 0
            for y_k in counter_yv.values():
                # 计算 \sum_k (p_k)^2，其中 p_k 是标签类别 k 在子数据集中的比例
                # Tips: p_k = y_k / n_v，其中 y_k 是类别 k 的样本数，n_v 是子数据集的总样本数
                # -------Your Code Here-------
                temp_v += 
            gini_v = 1 - temp_v
            
            # 如果 n_nv 为0，说明所有样本都落在特征 d 取值为 v 的子数据集中
            if n_nv==0:
                gini_nv = 0
            else:
                # 计算特征 d 取值不为 v 的子数据集的基尼系数 gini_nv
                temp_nv = 0
                for y_k in counter_ynv.values():
                    # 计算 \sum_k (p_k)^2，其中 p_k 是标签类别 k 在子数据集中的比例
                    # Tips: p_k = y_k / n_nv，其中 y_k 是类别 k 的样本数，n_nv 是子数据集的总样本数
                    # -------Your Code Here-------
                    temp_nv += 
                gini_nv = 1 - temp_nv

            # 计算加权基尼系数 gini_sum
            # -------Your Code Here-------
            gini_sum = 
            
            #如果 gini_sum < best_gini:
            #返回best_gini, best_dimension,best_value
            if gini_sum<best_gini:
                best_gini=gini_sum
                best_dimension=d
                best_value=unique_values[i]
                
    return best_gini, best_dimension,best_value

<span style="color:purple">7) 应用之前你在第4、5、6个部分编写的三个函数，在训练数据集'train_titanic.csv'上依次使用这些函数进行【一次】结点划分，并输出对应的最佳特征维数以及相应的信息增益值/信息增益率/(基尼系数和分类值)</span>

In [ ]:
#----your code here
best1_entropy, best1_dimension = find_opt_feature_gain(train_f, train_o)
print("最佳维数:",best1_dimension,"信息增益值:",best1_entropy)
data1,label1=split(train_f,train_o,best1_dimension)

best2_entropy, best2_dimension = find_opt_feature_gainratio(train_f, train_o)
print("最佳维数:",best2_dimension,"信息增益率:",best2_entropy)
data2,label2=split(train_f,train_o,best2_dimension)

best3_entropy, best3_dimension,best3_value= find_opt_feature_gini(train_f, train_o)
print("最佳维数:",best3_dimension,"基尼系数:",best3_entropy,"分类值:",best3_value)


最佳维数: 0 信息增益值: 0.10750711887455178
最佳维数: 0 信息增益率: 0.11339165967945304
最佳维数: 0 基尼系数: 0.2964915724641573 分类值: 0


**<font color = blue size=3>2) 任务二</font>**

任务二承接任务一，用【ID3】算法实现一棵完整的决策树。

<span style="color:purple">利用任务一中的find_opt_feature_entropy函数，完成DTree类中的TreeGenerate、train函数以完成决策树的构建。并完成DTree类中的predict函数来用构建好的决策树来对测试数据集进行预测并输出预测准确率。</span>

In [8]:
# 树结点类
class Node:
    def __init__(self, isLeaf=True, label=-1, feature_index=-1):
        self.isLeaf = isLeaf # isLeaf表示该结点是否是叶结点
        self.label = label # label表示该叶结点的label（当结点为叶结点时有用）
        self.feature_index = feature_index # feature_index表示该分支结点的划分特征的序号（当结点为分支结点时有用）
        self.children = {} # children表示该结点的所有孩子结点，dict类型，方便进行决策树的搜索
        
    def addNode(self, val, node):
        self.children[val] = node #为当前结点增加一个划分特征的值为val的孩子结点

In [ ]:
# 决策树类
class DTree:
    def __init__(self):
        self.tree_root = None #决策树的根结点
        self.possible_value = {} # 用于存储每个特征可能的取值
    
    def TreeGenerate(self, D, A):#D为数据集，A为特征集
        '''
        TreeGenerate函数用于递归构建决策树，伪代码参照课件中的“Algorithm 1 决策树学习基本算法”
            参数：
            - D: 数据集，二维数组。数据的前 D.shape[1]-1 列为特征，最后一列为对应的类别标签。
            - A: 可用的特征集合（一个列表），用于指导决策树的划分。当 A 为空或为 None 时，表示没有更多可用特征进行划分。
                 例如，A=[0,1]代表第0、第1个特征
                 注意不是特征的取值，而是特征的索引

            返回值：
            - 一个决策树节点（Node 对象），该节点可能为叶节点（记录类别标签）或内部节点（记录划分特征及其分支）。
        '''    
        train_f = D[:, :D.shape[1] - 1]# 提取特征
        train_o = D[:, D.shape[1] - 1: D.shape[1]]# 提取标签
        
        # 生成结点 node   
        node = Node()

        # 终止条件1：
        # if D中样本全属于同一类别C then
        #     将node标记为C类叶结点并返回
        # end if
        # =============================
        # Tips: 可能用到的函数
        # 1. np.unique(): 用于统计数据集D中标签的非重复值，如果只有一个非重复值，那么D中样本全部属于同一类别
        # 2. Node(isLeaf=True, label=..., feature_index=-1): 构造一个叶节点，label参数传入当前样本的类别C
        # -------Your Code Here-------
       
        
        # 终止条件2：
        # if A = Ø （无可用特征）OR D中样本在A上取值相同 then
        #     将node标记叶结点，其类别标记为D中样本数最多的类并返回 
        # end if
        # =============================
        # Tips: 可能用到的函数和语法：
        # 1. if A == None 或 bool(A) == False: 判断A是否为空
        # 2. np.unique(train_f[:, d]): 用于统计D中样本在特征集A中的某个特征d的非重复值，
        #                              如果只有一个非重复值，说明D中样本在特征d上取值相同
        #                              遍历A中所有特征，如果D中样本在A中所有特征上都只有一个非重复值，那么D中样本在A上取值相同
        # 3. np.argmax(np.bincount(train_o[:, 0])): 找到 train_o（类别标签数组）中出现次数最多的类别（即众数）
        # 4. node = Node(isLeaf=True, label=np.argmax(np.bincount(train_o[:, 0])), feature_index=-1)
        #    将node标记叶结点，其类别标记为D中样本数最多的类
        # -------Your Code Here-------


        # 开始构造非叶节点
        # 首先统计每个特征可能的取值，存储于决策树的possible_value属性中
        for d in A:
            self.possible_value[d] = np.unique(D[:, d])
        node.isLeaf = False
        
        # 从A中选择最优划分特征a_star
        # （选择信息增益最大的特征，用到上面实现的find_opt_feature_gain函数） 
        # -------Your Code Here-------
        _,a_star = 
        node.feature_index = a_star
        
        # 复制 A 并移除已选择的划分特征
        Av = A.copy()
        Av.remove(a_star)
        
        # for a_star 的每一个值a_star_v do
        #     为node 生成每一个分支node_a_star_v；令D_v表示D中在a_star上取值为a_star_v的样本子集
        #     if D_v 为空 then
        #         将分支结点标记为叶结点，其类别标记为D中样本最多的类
        #     else
        #         递归调用TreeGenerate(D_v,A-{a_star}) 创建子树
        #     end if
        #     将子节点加入树
        # end for
        # =================================
        # Tips: 可能用到的函数或语法
        # 1. self.possible_value[a_star]或者np.unique(D[:, a_star]): 获得a_star特征的非重复值，用于遍历
        # 2. Dv = D[np.where(D[:, a_star] == a_star_v)]表示D中在a_star上取值为a_star_v的样本子集:
        #    - np.where() 接受一个布尔数组作为条件，返回满足条件（即布尔值为 True）的元素的索引。
        #    - np.where(D[:, a_star] == a_star_v) 会返回一个索引数组，
        #      这些索引指明了 D 数组第 a_star 列中所有等于 a_star_v 的元素所在的行号。
        # 3. np.size(Dv): 如果样本子集Dv的大小为0，则Dv为空集
        # 4. Node(isLeaf=True, label=np.argmax(np.bincount(D_o[:,0])), feature_index=-1): 将分支结点标记为叶结点，其类别标记为D中样本最多的类
        # 5. node.addNode(val=a_star_v, node=node_a_star_v): 将子节点加入树
        # -------Your Code Here-------
            

        # 返回当前节点
        return node

 
    def train(self, D):
        '''
        train函数调用TreeGenerate函数来递归地生成决策树
    
        '''
        D = np.array(D) # 将Dataframe对象转换为numpy矩阵（也可以不转，自行决定做法）
        A = set(range(D.shape[1] - 1)) # 特征集A
        
        #记下每个特征可能的取值
        for every in A:
            self.possible_value[every] = np.unique(D[:, every])
        
        # 递归地生成决策树，并将决策树的根结点赋值给self.tree_root
        # 使用上面实现的TreeGenerate函数
        # -------Your Code Here-------
        self.tree_root = 
        return

    
    
    
    def predict(self, D):
        '''
        predict函数对测试集D进行预测， 并输出预测准确率（预测正确的个数 / 总数据数量）
        
        '''
        D = np.array(D) # 将Dataframe对象转换为numpy矩阵（也可以不转，自行决定做法）

        # 实现思路：
        # 1. 初始化变量：确定样本数量 n，创建一个与样本数量匹配的 labels 数组存储每个样本的预测标签，以及用 correct 计数预测正确的样本数；
        # 2. 对每一个样本i in range(n)：
        #    a. 从决策树的根结点开始（即 self.tree_root），记当前结点x=self.tree_root；
        #    b. 利用 while 循环不断判断当前结点x是否为分支节点（x.isLeaf == False），
        #       如果是，则根据样本i在当前结点划分特征（x.feature_index）上的取值，从结点的 children 字典中选出对应的子结点（即x=x.children[d[x.index]]，其中d为当前的样本i）；
        #    c. 当遍历到叶节点后，该叶结点的标签就是样本i的预测标签，将该叶节点上的 label 存入预测标签数组；
        #    d. 同时，将预测标签与真实标签（样本i的最后一列 D[i, D.shape[1]-1]）进行比较，统计预测正确的个数；
        # 3. 计算并返回预测准确率
        # -------Your Code Here-------
        
        return acc


In [ ]:
# 构建决策树
train_frame = pd.read_csv('train_titanic.csv')
dt = DTree()
dt.train(train_frame)

# 利用构建好的决策树对测试数据集进行预测，输出预测准确率（预测正确的个数 / 总数据数量）
test_frame = pd.read_csv('test_titanic.csv')
acc=dt.predict(test_frame)
print("预测准确率:",acc)

In [ ]:
#展示生成的决策树结构
def display_tree(node, indent=''):
    if node.isLeaf:
        print(indent + "Leaf Node: label =", node.label)
    else:
        print(indent + "Branch Node: feature_index =", node.feature_index)
        for value, child in node.children.items():
            print(indent + "|--> Child Value:", value)
            display_tree(child, indent + "   ")

display_tree()

**<font color = blue size=4>第三部分:作业提交</font>**

一、本次实验分两周完成，实验课下课前提交完成代码 要求:

1)文件格式为：学号-姓名.ipynb

2)【不要】提交文件夹、压缩包、数据集等无关文件，只需提交单个ipynb文件即可，如果交错请到讲台前联系助教，删掉之前的错误版本后再进行提交  

二、实验课件获取地址:https://www.jianguoyun.com/p/DUImtU8Qp5WhChixu4sGIAA

课堂课件获取地址:https://www.jianguoyun.com/p/Ddk4kPQQp5WhChiXwYcGIAA